baseURL = "https://bigclown.com/"
disableKinds = ["RSS", "sitemap"]
languageCode = "en"
pygmentsCodeFences = true
pygmentsUseClasses = true
title = "BigClown"

[blackfriday]
smartypants = false

[Languages]
[Languages.en]
weight = 1
languageName = "English"
countryCode = "gb"
[Languages.cs]
weight = 2
languageName = "Čeština"
countryCode = "cz"

[params]
menuNames = ["main"]
productionURL = "https://biglclown.com"
